### ISSUE TITLE
Download goal: No renditions are included, but AEM publish does not trigger update_asset workflow to create them

### ISSUE THREAD

**Issue by henrykuijpers** [wcm-io/io.wcm.maven.aem-global-parent#13]
https://github.com/wcm-io/io.wcm.maven.aem-global-parent/blob/4b08ec3a5fbcb047f24381f288575cdcc3dea7ac/pom.xml#L418

This makes sure to not include renditions in the SCM, which is of course very nice to have. When installing the package on the author environment, the renditions are automatically created because of the update_asset workflow launcher.

However, this launcher is only active on author (runmodes=author), due to which the assets will not have any renditions on the publish environment.

When activating assets from the author environment to the publish, the asset including all metadata & renditions will be activated to the publish environment. 

In the end, it causes the assets to be available in the author environment with renditions, and available without renditions in the publish.

@stefanseifert  How are you handling this "feature" in your projects? How do you make the renditions available in your publish environment as well?

**Comment by henrykuijpers** [comment]
Any thoughts on this?

**Comment by stefanseifert** [comment]
the mentioned line excludes only some of the auto-generated renditions, namly all the cq5dam.thumbnail in the name. this should by only those generated for usage in the author UI itself, usually those should not be used on live website? if you are actively using those on publish, you should probably remove that exclude and overwrite the "excludeFiles" section.
